artifact_location: /Users/georgkaltenbrunner/python/MLDatenAnonymisiert/mlflowruns/0
creation_time: 1752237559905
experiment_id: '0'
last_update_time: 1752237559905
lifecycle_stage: active
name: Default
